name: Publish

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: all

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm install
      - name: 'Package for linux'
        if: matrix.platform == 'linux'
        run: npx vsce package --target linux-x64, linux-arm64, linux-armhf, alpine-x64, alpine-arm64
      - name: 'Package for all'
        if: matrix.platform == 'all'
        run: npx vsce package
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: "*.vsix"

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: success() && startsWith( github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
      - run: npx vsce publish --packagePath $(find . -iname *.vsix)
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}